<a href="https://colab.research.google.com/github/badrinarayanan02/machine_learning/blob/main/2348507_AMLlab10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Reinforcement Learning**

Python script for implementing Q-Learning menthod.
Q learning is a value-based method of supplying information to inform which action an agent should
take.

There are five rooms in a building which are connected by doors.

Each room is numbered 0 to 4,
The outside of the building can be one big outside area(5),
Doors number 1 and 4 lead into the building from room 5,
Display / print initial matrix understanding the layout given below.
Implement Q-Learning method for generating all possible states and actions. Display / print final
Convergence Value matrix.

In [ ]:
import numpy as np

In [ ]:
num_rooms = 5

num_actions = 4

layout = [
    [0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0],
]


Q learning paramaters

In [ ]:
alpha = 0.1
gamma = 0.9
epsilon = 0.1

# Initialize Q matrix
Q = np.zeros((num_rooms, num_actions))

Getting Available Actions

In [ ]:
def get_available_actions(state):
    return [action for action in range(num_actions) if layout[state][action] == 1]

Q Learning Algorithm

In [ ]:
def q_learning():
    num_episodes = 1000

    for episode in range(num_episodes):
        current_state = np.random.randint(num_rooms)
        done = False

        while not done:
            available_actions = get_available_actions(current_state)

            if not available_actions:
                break

            if np.random.uniform(0, 1) < epsilon:
                action = np.random.choice(available_actions)
            else:
                action = np.argmax(Q[current_state])

            next_state = np.argmax(layout[current_state])
            reward = 1 if next_state == num_rooms - 1 else 0  # Reward 1 if outside, else 0


            Q[current_state, action] = (1 - alpha) * Q[current_state, action] + alpha * (reward + gamma * np.max(Q[next_state]))

            current_state = next_state
            done = (current_state == num_rooms - 1)


print("Initial Layout Matrix:")
print(np.array(layout))

q_learning()

print("\nFinal Q Matrix (Convergence Value Matrix):")
print(Q)

Initial Layout Matrix:
[[0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]]

Final Q Matrix (Convergence Value Matrix):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Inference:** This indicates that after training, the Q values for all state-action pairs have converged to zero. This might be due to the limited exploration or insufficient training episodes.
